const axios = require("axios");
const cheerio = require("cheerio");
const XLSX = require("xlsx"); // 引入xlsx模塊

async function extractContent(url) {
  const response = await axios.get(url);
  const $ = await cheerio.load(response.data);
  // 提取題目内容
  const questionText = await $(".question-body.mt-3.pt-3.border-top")
    .find("p.card-text")
    .text()
    .trim();

  //提取選項
  const choices = await $(".question-choices-container")
    .find(".multi-choice-item")
    .map((i, el) => {
      // 提取與排序每個選項的文字，並移除多餘空格與字符
      const choiceLetter = $(el).find(".multi-choice-letter").text().trim();
      const choiceText = $(el).clone().children().remove().end().text().trim();

      return choiceLetter + " " + choiceText;
    })
    .get();
  const formatChoices = await choices.join("\n").trim();

  // 提取答案

  const progressContent = await $(".voted-answers-tally.d-none").text().trim();
  const correctAns = await $(".correct-answer").text().trim();

  return { questionText, formatChoices, progressContent, correctAns };
}

// 探尋並存檔至Excel，SAA之言
async function searchAndSaveToExcel(startPage, endPage) {
  let data = []; // 數據資料箱

  const targetUrl = [
    "https://www.examtopics.com/discussions/amazon/view/111102-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82499-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81327-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/83281-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81314-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/84287-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81304-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82972-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82971-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81300-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81197-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82906-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81182-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82811-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81175-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82792-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81093-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81090-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82431-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82401-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82400-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/83189-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81082-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81081-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82268-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81073-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82263-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82259-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82258-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82020-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82018-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81698-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/80772-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/80766-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/80742-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/80735-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/80737-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68933-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68931-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/69004-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68994-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68971-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68990-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68970-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68910-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68951-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67775-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67998-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67881-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67771-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67959-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68072-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68246-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68070-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67897-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67846-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67879-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61056-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61066-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61082-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61080-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/59968-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/60041-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/60040-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/60036-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/60035-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/59983-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53854-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53911-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53910-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46383-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53909-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53893-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/51346-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46545-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46539-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46394-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46519-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46685-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46514-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46507-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46506-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46505-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/47557-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46494-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46476-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46462-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46446-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46444-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46443-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46820-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46434-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46431-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46413-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46400-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46390-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46634-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46681-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46630-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46704-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43800-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43746-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43792-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43782-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43777-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43730-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35860-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35772-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35857-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35818-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35813-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35837-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35643-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/30055-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/29740-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/29778-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/29775-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68880-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/29768-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/29752-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27877-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27875-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27798-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27846-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27772-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/22180-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81535-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53895-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/29757-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43725-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/99381-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35832-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/85914-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81531-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/24851-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/59966-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/84375-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46464-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68035-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27893-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46415-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46546-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/87927-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46485-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46466-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46397-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82861-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/98425-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27943-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43779-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35807-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46488-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46547-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/21797-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67840-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43900-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61526-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43797-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43778-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27985-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/22050-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/21822-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46534-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/98427-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35677-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46486-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46410-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81445-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46699-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35852-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35688-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27774-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/99458-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/84800-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/99384-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61293-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27928-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81439-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46803-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46469-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46457-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46451-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46430-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46419-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46401-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61104-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/22177-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35848-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46407-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43713-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46428-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/69000-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/83984-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/83124-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81194-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81103-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81078-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/51506-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/80958-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35861-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/29751-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27855-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61151-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46477-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/92983-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61039-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61040-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/83867-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/60215-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/83982-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68069-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/83199-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43702-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/54004-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35844-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/90064-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/90062-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/90061-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/28087-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27863-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43798-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43791-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27775-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61107-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61312-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27844-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/88416-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46411-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/88030-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68997-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68993-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/87682-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81315-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82328-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/80937-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68991-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35849-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/60023-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/59985-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/59984-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46470-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46839-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67844-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/28010-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43723-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/22024-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35838-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46915-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35801-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/30057-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27926-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27935-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/80218-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/28070-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/21819-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/22139-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68089-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81298-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43704-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/60046-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68955-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68952-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81422-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81104-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/80951-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/24836-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81086-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/51511-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/84407-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/84315-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/83285-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53849-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81319-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/84314-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82504-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81434-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46515-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/83282-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/84686-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/84543-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/84409-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81188-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/84374-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/83197-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/84360-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/84294-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/84282-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81302-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/84249-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81186-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/84228-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/84222-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82324-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81100-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81098-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81092-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81077-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81076-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82317-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81074-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/80761-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/80755-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/80753-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/80734-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27787-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82325-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82320-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/29738-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82022-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81928-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81927-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/80738-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/83752-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/51354-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46482-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68959-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46629-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43813-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67989-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68057-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61058-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61162-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/59986-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53879-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/51510-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/22049-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/51357-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/51356-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/51235-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/81297-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82969-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/80330-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/47133-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46521-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/82797-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/28077-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27880-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27934-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27933-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46492-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46450-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46438-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43790-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/30056-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61420-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27882-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27850-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27930-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43780-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27832-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46429-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67871-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68875-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35820-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35679-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46651-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/22041-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46503-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46502-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35859-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27825-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35817-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/21829-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/29748-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27828-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35683-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35669-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53840-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61147-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/22048-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46682-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27795-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46452-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46550-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27688-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/21966-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68998-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67968-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68995-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67694-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/59961-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61074-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/59958-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61063-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46480-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27991-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68965-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35706-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35854-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/28052-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35845-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/29765-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46392-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61269-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27888-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/29772-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53852-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/59981-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61062-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27700-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53927-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/69003-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/51344-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46408-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68967-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46398-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46414-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46484-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/21831-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53877-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/59960-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43781-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27889-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67870-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/60039-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61069-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/60042-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61041-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53928-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67936-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61145-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67834-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68034-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46467-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46393-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67967-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46544-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46449-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/47140-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46422-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61067-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61150-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61070-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/29782-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/24824-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46425-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35858-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27777-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53908-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68833-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61072-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46491-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53881-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/60048-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/24823-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27898-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/69077-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46395-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/51347-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53926-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27941-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/51358-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46463-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/59967-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/69005-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/29776-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61161-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46406-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43795-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67932-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/30065-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67693-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67958-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/51349-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27923-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/21793-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46386-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/51507-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46412-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27932-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61146-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46523-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/29756-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61212-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68999-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27830-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/29746-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46489-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43783-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46396-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/53845-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27891-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61073-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68022-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46416-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35809-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27851-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/51352-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/21824-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67999-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43796-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/21834-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35856-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35855-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27865-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/69002-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/29762-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/51350-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/59982-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46461-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46402-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68306-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43729-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27903-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61142-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/67826-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43799-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27857-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/35884-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27773-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61672-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/68961-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46472-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46501-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/43816-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/61446-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/27873-exam-aws-certified-solutions-architect-associate-saa-c02/",
    "https://www.examtopics.com/discussions/amazon/view/46405-exam-aws-certified-solutions-architect-associate-saa-c02/"
];



  console.log("This is start crawler");
  let page = 0;
  for (page; page < targetUrl.length; page++) {

    try {
      console.log("This is try crawler, ", page);

      const res = await extractContent(targetUrl[page]); // 每个連結提取内容
      const content = {
        index: page + 1,
        questionText: res.questionText || "",
        formatChoices: res.formatChoices || "",
        progressContent: res.progressContent || "",
        correctAns: res.correctAns || "",
      };
      content.URL = targetUrl[page];
      data.push(content);
      console.log("This is content, ", content);

    } catch (error) {
      page--;
      console.error(`Failed to fetch page 1`, error);
    }
  }

  // 將資料儲入Excel
  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "SaaLinks");
  XLSX.writeFile(workbook, "SaaLinks.xlsx");

  console.log("Excel file has been saved successfully.");
}

// 將範圍設為從第1頁到第486頁，尋找 SAA 相關內容並儲存至Excel檔案
searchAndSaveToExcel(1, 486);
